# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ProMCDA.mcda.models.base_model_ import Model
from ProMCDA.mcda.models.configuration_monte_carlo_sampling import ConfigurationMonteCarloSampling  # noqa: F401,E501
from ProMCDA.mcda.models.configuration_robustness import ConfigurationRobustness  # noqa: F401,E501
from ProMCDA.mcda.models.configuration_sensitivity import ConfigurationSensitivity  # noqa: F401,E501
from ProMCDA.mcda import util


class Configuration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input_matrix: Dict[str, Dict[str, float]]=None, weights: List[float]=None, polarity: List[str]=None, sensitivity: ConfigurationSensitivity=None, robustness: ConfigurationRobustness=None, monte_carlo_sampling: ConfigurationMonteCarloSampling=None):  # noqa: E501
        """Configuration - a model defined in Swagger

        :param input_matrix: The input_matrix of this Configuration.  # noqa: E501
        :type input_matrix: Dict[str, Dict[str, float]]
        :param weights: The weights of this Configuration.  # noqa: E501
        :type weights: List[float]
        :param polarity: The polarity of this Configuration.  # noqa: E501
        :type polarity: List[str]
        :param sensitivity: The sensitivity of this Configuration.  # noqa: E501
        :type sensitivity: ConfigurationSensitivity
        :param robustness: The robustness of this Configuration.  # noqa: E501
        :type robustness: ConfigurationRobustness
        :param monte_carlo_sampling: The monte_carlo_sampling of this Configuration.  # noqa: E501
        :type monte_carlo_sampling: ConfigurationMonteCarloSampling
        """
        self.swagger_types = {
            'input_matrix': Dict[str, Dict[str, float]],
            'weights': List[float],
            'polarity': List[str],
            'sensitivity': ConfigurationSensitivity,
            'robustness': ConfigurationRobustness,
            'monte_carlo_sampling': ConfigurationMonteCarloSampling
        }

        self.attribute_map = {
            'input_matrix': 'inputMatrix',
            'weights': 'weights',
            'polarity': 'polarity',
            'sensitivity': 'sensitivity',
            'robustness': 'robustness',
            'monte_carlo_sampling': 'monteCarloSampling'
        }
        self._input_matrix = input_matrix
        self._weights = weights
        self._polarity = polarity
        self._sensitivity = sensitivity
        self._robustness = robustness
        self._monte_carlo_sampling = monte_carlo_sampling

    @classmethod
    def from_dict(cls, dikt) -> 'Configuration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Configuration of this Configuration.  # noqa: E501
        :rtype: Configuration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input_matrix(self) -> Dict[str, Dict[str, float]]:
        """Gets the input_matrix of this Configuration.

        An array where the columns represent the indicators and the rows their values for different alternatives.  # noqa: E501

        :return: The input_matrix of this Configuration.
        :rtype: Dict[str, Dict[str, float]]
        """
        return self._input_matrix

    @input_matrix.setter
    def input_matrix(self, input_matrix: Dict[str, Dict[str, float]]):
        """Sets the input_matrix of this Configuration.

        An array where the columns represent the indicators and the rows their values for different alternatives.  # noqa: E501

        :param input_matrix: The input_matrix of this Configuration.
        :type input_matrix: Dict[str, Dict[str, float]]
        """
        if input_matrix is None:
            raise ValueError("Invalid value for `input_matrix`, must not be `None`")  # noqa: E501

        self._input_matrix = input_matrix

    @property
    def weights(self) -> List[float]:
        """Gets the weights of this Configuration.

        The weights associated to the indicators.  # noqa: E501

        :return: The weights of this Configuration.
        :rtype: List[float]
        """
        return self._weights

    @weights.setter
    def weights(self, weights: List[float]):
        """Sets the weights of this Configuration.

        The weights associated to the indicators.  # noqa: E501

        :param weights: The weights of this Configuration.
        :type weights: List[float]
        """
        if weights is None:
            raise ValueError("Invalid value for `weights`, must not be `None`")  # noqa: E501

        self._weights = weights

    @property
    def polarity(self) -> List[str]:
        """Gets the polarity of this Configuration.

        The polarity of an indicator indicates whether its rising value adds positively or negatively to the MCDA scores.  # noqa: E501

        :return: The polarity of this Configuration.
        :rtype: List[str]
        """
        return self._polarity

    @polarity.setter
    def polarity(self, polarity: List[str]):
        """Sets the polarity of this Configuration.

        The polarity of an indicator indicates whether its rising value adds positively or negatively to the MCDA scores.  # noqa: E501

        :param polarity: The polarity of this Configuration.
        :type polarity: List[str]
        """
        allowed_values = ["+", "-"]  # noqa: E501
        if not set(polarity).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `polarity` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(polarity) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._polarity = polarity

    @property
    def sensitivity(self) -> ConfigurationSensitivity:
        """Gets the sensitivity of this Configuration.


        :return: The sensitivity of this Configuration.
        :rtype: ConfigurationSensitivity
        """
        return self._sensitivity

    @sensitivity.setter
    def sensitivity(self, sensitivity: ConfigurationSensitivity):
        """Sets the sensitivity of this Configuration.


        :param sensitivity: The sensitivity of this Configuration.
        :type sensitivity: ConfigurationSensitivity
        """
        if sensitivity is None:
            raise ValueError("Invalid value for `sensitivity`, must not be `None`")  # noqa: E501

        self._sensitivity = sensitivity

    @property
    def robustness(self) -> ConfigurationRobustness:
        """Gets the robustness of this Configuration.


        :return: The robustness of this Configuration.
        :rtype: ConfigurationRobustness
        """
        return self._robustness

    @robustness.setter
    def robustness(self, robustness: ConfigurationRobustness):
        """Sets the robustness of this Configuration.


        :param robustness: The robustness of this Configuration.
        :type robustness: ConfigurationRobustness
        """
        if robustness is None:
            raise ValueError("Invalid value for `robustness`, must not be `None`")  # noqa: E501

        self._robustness = robustness

    @property
    def monte_carlo_sampling(self) -> ConfigurationMonteCarloSampling:
        """Gets the monte_carlo_sampling of this Configuration.


        :return: The monte_carlo_sampling of this Configuration.
        :rtype: ConfigurationMonteCarloSampling
        """
        return self._monte_carlo_sampling

    @monte_carlo_sampling.setter
    def monte_carlo_sampling(self, monte_carlo_sampling: ConfigurationMonteCarloSampling):
        """Sets the monte_carlo_sampling of this Configuration.


        :param monte_carlo_sampling: The monte_carlo_sampling of this Configuration.
        :type monte_carlo_sampling: ConfigurationMonteCarloSampling
        """
        if monte_carlo_sampling is None:
            raise ValueError("Invalid value for `monte_carlo_sampling`, must not be `None`")  # noqa: E501

        self._monte_carlo_sampling = monte_carlo_sampling
