# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ProMCDA.mcda.models.base_model_ import Model
from ProMCDA.mcda.models.sensitivity_ranked_alternatives_inner import SensitivityRankedAlternativesInner  # noqa: F401,E501
from ProMCDA.mcda import util


class SensitivityRankedAlternatives(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """SensitivityRankedAlternatives - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SensitivityRankedAlternatives':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SensitivityRankedAlternatives of this SensitivityRankedAlternatives.  # noqa: E501
        :rtype: SensitivityRankedAlternatives
        """
        return util.deserialize_model(dikt, cls)
