# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PoissonIndicatorValues(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, rate: float=None):  # noqa: E501
        """PoissonIndicatorValues - a model defined in Swagger

        :param rate: The rate of this PoissonIndicatorValues.  # noqa: E501
        :type rate: float
        """
        self.swagger_types = {
            'rate': float
        }

        self.attribute_map = {
            'rate': 'rate'
        }
        self._rate = rate

    @classmethod
    def from_dict(cls, dikt) -> 'PoissonIndicatorValues':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PoissonIndicatorValues of this PoissonIndicatorValues.  # noqa: E501
        :rtype: PoissonIndicatorValues
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rate(self) -> float:
        """Gets the rate of this PoissonIndicatorValues.

        The average number of events occurring in a fixed interval of time or space for a specific alternative.  # noqa: E501

        :return: The rate of this PoissonIndicatorValues.
        :rtype: float
        """
        return self._rate

    @rate.setter
    def rate(self, rate: float):
        """Sets the rate of this PoissonIndicatorValues.

        The average number of events occurring in a fixed interval of time or space for a specific alternative.  # noqa: E501

        :param rate: The rate of this PoissonIndicatorValues.
        :type rate: float
        """
        if rate is None:
            raise ValueError("Invalid value for `rate`, must not be `None`")  # noqa: E501

        self._rate = rate
